### ISSUE TITLE
Menu klassiek/mijn parser rekenmachine niet volledig duidelijk

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#10]
De knop om tussen de twee machines te wisselen is niet volledig duidelijk. De knop kan geïnterpreteerd worden als "Ga naar Klassiek rekenmachine" of "Ga naar Mijn rekenmachine", wat niet het geval is.

Gelieve hier een (uitklapbare) menu van te maken, waarbij men 1 van de twee kan selecteren en waar de huidige rekenmachine dan aangevinkt(of geselecteerd) staat.
![image](https://user-images.githubusercontent.com/11158784/61030775-7004fe80-a3be-11e9-9350-cfa706b7e07f.png)

**Comment by L-Henry** [comment]
Is nu met combobox.
