### ISSUE TITLE
Winforms UI projectnaam verwarrend

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#2]
De naam van het UI project "CalculatorApp.Domain" is verwarrend. Domain is een aanduiding voor de domeinlaag, wat een van de laagste niveaus binnen een applicatie gaat aanduiden.
best omvormen naar "CalculatorApp.Ui" of "CalculatorApp.WinForms". 

Ook zie ik dat de naam van je ClassLibrary "RekenmachineClassLibrary" niet in lijn is met je winforms project. Dit is een detail, maar het is beter om zoveel mogelijk dezelfde projectnamen en namespaces te gebruiken binnen 1 solution, om zulke verwarringen op te lossen.

Als je zo'n projectnaam aanpast, vergeet dan niet in de properties van dat project ook alle namespaces in de classes aan te passen, alsook de default namespace en assembly name aan te passen in de project properties.

**Comment by L-Henry** [comment]
Aangepast.
