### ISSUE TITLE
Dubbele event handlers

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#3]
Als je de event handlers bekijkt in het form, zie je dat er 1 event handler per button click is. Dit is in de meeste gevallen onnodig. Je kan 1 event assignen aan elke button met dezelfde functionaliteit (bvb de getallen), en dan de text van de button doorgeven aan de textbox.

https://github.com/L-Henry/Rekenmachine/blob/6a55ec98253e2efbd41d4629fdeebe6e87f9151c/CalculatorApp.Domain/RekenmachineForm.cs#L54

**Comment by L-Henry** [comment]
Aangepast voor nummer buttons.
