### ISSUE TITLE
Splits methode in twee methodes: BinairNaarDecimaal en DecimaalNaarBinair

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#4]
De parameter int richting is verwarrend en in principe onnodig. Moest je toch een parameter voor de richting willen gebruiken, dan is het beter om een Enum Richting te gebruiken, maar aangezien deze methode expliciet niets anders doet dan binair naar decimaal of decimaal naar binair omvormen, is het beter om dit op te splitsen naar twee methodes en de logica van de richting te implementeren buiten deze methode

https://github.com/L-Henry/Rekenmachine/blob/6a55ec98253e2efbd41d4629fdeebe6e87f9151c/RekenmachineClassLibrary/MijnParserRekenmachine.cs#L11

**Comment by L-Henry** [comment]
Gesplitst in twee methodes en in apparte klasse gestopt waarin meer converteer methodes zouden kunnen toegevoegd worden.
Richting is verwijderd als input. Paramater richtng was er eigenlijk enkel om als default richting 1 (dec -> binair) mee te geven. Maar dat was deel van de console applicatie. Niet meer van toepassing voor winforms omgeving.
