### ISSUE TITLE
Berekenfunctie moet opgesplitst worden in meerdere methodes

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#5]
Er zit heel veel logica in de methode Bereken, waardoor dit voor andere developers moeilijk te lezen is wat er eigenlijk gebeurt als men specifieke lijnen leest binnen deze methode. Best is om dit op te splitsen in meerdere methodes (haakjes, maal, som en verschil,...), die dan worden aangesproken via Bereken. Ook zie ik veel stukken code die continu weerkeren (while loops enz,...). Indien 1 van die stukken code een bug bevat, is de kans groot dat je deze bug op meerdere plekken zal moeten fixen. Beter is om zulke wederkerende stukken code te groeperen in 1 methode. 

https://github.com/L-Henry/Rekenmachine/blob/6a55ec98253e2efbd41d4629fdeebe6e87f9151c/RekenmachineClassLibrary/MijnParserRekenmachine.cs#L48

**Comment by L-Henry** [comment]
Opgesplitst in methodes.
De loops lijken op elkaar, maar zijn beetje verschillend.
