### ISSUE TITLE
Window kan vergroot/verkleint worden, waardoor layout niet klopt

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#6]
Best is om ervoor te zorgen dat het scherm helemaal niet kan vergroten of verkleinen. Tijdens de cursus over UWP zullen we meer zien over hoe de UI mee gaan kunnen veranderen met de grootte van het scherm.

![image](https://user-images.githubusercontent.com/11158784/61028600-57461a00-a3b9-11e9-8200-4b9f7d0a017d.png)

**Comment by L-Henry** [comment]
Aangepast zodat window niet kan vergroot of verkleint worden.
