### ISSUE TITLE
Cijfer wordt toegevoegd aan uitkomst ipv nieuwe bewerking.

### ISSUE THREAD

**Issue by braekstuv** [L-Henry/Rekenmachine#7]
Repro steps:
1. geef 999 in
2. klik op 1/x
3. klik op 6 (of ander cijfer)

Verwacht resultaat: er wordt een nieuwe bewerking opgestart

Actueel resultaat: het cijfer 6 wordt toegevoegd aan de uitkomst van de vorige bewerking

![image](https://user-images.githubusercontent.com/11158784/61029235-dd169500-a3ba-11e9-931f-0f7dcca3ed76.png)

**Comment by L-Henry** [comment]
Deze lijkt te werken nu, hopelijk echt fixed.
